[package]
name = "tauri-plugin-env-var"
version = "0.0.0"
authors = ["You"]
description = ""
edition = "2021"
rust-version = "1.60"
exclude = ["/examples"]

[dependencies]
tauri = { version = "1.5.*" }
serde = { version = "1.0.*" }
regex = "1.10.*"
